CREATE TABLE PRODUCT_BOARD
(
	P_NAME VARCHAR2(100),
	P_PRICE VARCHAR2(100),
	P_IMG VARCHAR2(100),
	P_COUNT NUMBER(10),
	P_B_NUM NUMBER(10),
	P_B_MINI_TITLE VARCHAR2(100),
	P_B_CONTENT VARCHAR2(100),
	P_B_LIKE NUMBER(10),
	P_B_READCNT NUMBER(10),
	P_B_YN VARCHAR2(2),
	P_B_WARN VARCHAR2(100),
	P_B_TAG VARCHAR2(2000),
	M_ID VARCHAR2(50),
	P_COUNT_LIMIT NUMBER(3)
)


CREATE TABLE CUSTOM_BOARD
(
	C_B_NUM NUMBER(10),
	C_B_MINI_TITLE VARCHAR2(100),
	C_B_CONTENT VARCHAR2(),
	C_B_LIKE NUMBER(10),
	C_B_READCNT NUMBER(10),
	C_B_TAG VARCHAR2(2000),
	C_B_WARN VARCHAR2(100),
	C_B_NAME VARCHAR2(100),
	C_B_PRICE NUMBER(10),
	M_ID VARCHAR2(50)
)

CREATE TABLE HOME_QNA
(
	H_Q_NUM NUMBER(10),
	H_Q_CONTENT VARCHAR2(4000),
	H_Q_TITLE VARCHAR2(500),
	H_Q_DATE DATE,
	M_ID VARCHAR2(50)
)

CREATE TABLE H_QNA_COM
(
	H_Q_C_NUM NUMBER(10),
	H_Q_NUM NUMBER(10),
	H_Q_C_CONTENT VARCHAR2(4000),
	H_Q_C_DATE DATE
)



CREATE TABLE PRODUCT_QNA
(
	P_Q_NUM NUMBER(10),
	P_Q_CONTENT VARCHAR2(4000),
	P_B_NUM NUMBER(10),
	P_Q_DATE DATE,
	M_ID VARCHAR2(100)
)

CREATE TABLE P_QNA_COM
(
	P_Q_C_NUM NUMBER(10),
	P_Q_NUM NUMBER(10),
	P_Q_C_CONTENT VARCHAR2(4000),
	P_Q_C_DATE DATE
)

CREATE TABLE PRODUCT_REVIEW
(
	P_R_NUM NUMBER(10),
	P_B_NUM NUMBER(10),
	P_R_CONTENT VARCHAR2(4000),
	P_R_DATE DATE,
	M_ID VARCHAR2(50),
	P_R_LIKE NUMBER(5),
	P_R_BLACK NUMBER(1),
	P_R_FILE VARCHAR2(1000)
)

CREATE TABLE P_REVIEW_COM
(
	P_R_C_NUM NUMBER(10),
	P_R_NUM NUMBER(10),
	P_R_C_CONTENT VARCHAR2(4000),
	P_R_C_DATE DATE
)