CREATE TABLE PRODUCT_ORDER
(
	P_O_NUM NUMBER,
	P_O_DATE DATE,
	P_O_BOOKDATE DATE,
	P_O_CNT NUMBER,
	P_O_PRICE NUMBER(10),
	P_O_TEXT VARCHAR2(60),
	P_O_REC_NAME VARCHAR2(50),
	P_O_REC_CP VARCHAR2(50),
	P_O_REC_POST VARCHAR2(10),
	P_O_REC_BASIC_ADDR VARCHAR2(150),
	P_O_REC_DETAIL_ADDR VARCHAR2(100),
	P_O_MEMO VARCHAR2(300),

	M_ID VARCHAR2(50),
	P_B_NUM NUMBER(10),
	BIZ_DELIVERY NUMBER(10),
	D_STATUS_NUM NUMBER,
)

CREATE TABLE CUSTOM_ORDER
(
	C_O_NUM NUMBER,
	C_O_DATE DATE,
	C_O_BOOKDATE DATE,
	C_O_CNT NUMBER,
	C_O_PRICE NUMBER(10),
	C_O_TEXT VARCHAR2(60),
	C_O_SHEET VARCHAR2(20),
	C_O_TOPPING VARCHAR2(20),
	C_O_CREAM VARCHAR2(20),
	C_O_REC_NAME VARCHAR2(50),
	C_O_REC_CP VARCHAR2(50),
	C_O_REC_POST VARCHAR2(10),
	C_O_REC_BASIC_ADDR VARCHAR2(150),
	C_O_REC_DETAIL_ADDR VARCHAR2(100),
	C_O_MEMO VARCHAR2(300),
	
	M_ID VARCHAR2(50),
	C_B_NUM VARCHAR2(10),
	BIZ_DELIVERY NUMBER(10),
	D_STATUS_NUM NUMBER
)

CREATE TABLE CUSTOM_SHEET
(
	M_ID VARCHAR2(50),
	SH_NUM VARCHAR2(20),
	SH_NAME VARCHAR2(50),
	SH_PRICE NUMBER
)

CREATE TABLE CUSTOM_TOPPING
(
	M_ID VARCHAR2(50),
	TP_NUM VARCHAR2(20),
	TP_NAME VARCHAR2(50),
	TP_PRICE NUMBER
)

CREATE TABLE CUSTOM_CREAM
(
	M_ID VARCHAR2(50),
	CR_NUM VARCHAR2(20),
	CR_NAME VARCHAR2(50),
	CR_PRICE NUMBER
)