ALTER TABLE CUSTOM_BOARD
	DROP
		CONSTRAINT FK_MEMBER_TO_CUSTOM_BOARD
		CASCADE;

ALTER TABLE CUSTOM_BOARD
	DROP
		PRIMARY KEY
		CASCADE
		KEEP INDEX;

DROP INDEX PK_CUSTOM_BOARD;

/* 커스터마이징 케이크 상세페이지 */
DROP TABLE CUSTOM_BOARD 
	CASCADE CONSTRAINTS;

/* 커스터마이징 케이크 상세페이지 */
CREATE TABLE CUSTOM_BOARD (
	C_B_NUM NUMBER NOT NULL, /* 게시글 번호 */
	M_ID VARCHAR2(50) NOT NULL, /* 회원 아이디 */
	C_B_MINI_TITLE VARCHAR2(100) NOT NULL, /* 게시글 소제목 */
	C_B_MINI_CONTENT VARCHAR2(2000) NOT NULL, /* 게시글 소내용 */
	C_B_CONTENT VARCHAR2(4000) NOT NULL, /* 게시글 내용 */
	C_B_LIKE NUMBER NOT NULL, /* 게시글 좋아요 수 */
	C_B_READCNT NUMBER NOT NULL, /* 게시글 조회 수 */
	C_B_TAG VARCHAR2(2000) NOT NULL, /* 게시글 태그 */
	C_B_WARN VARCHAR2(2000) NOT NULL, /* 예약시 주의사항 */
	C_B_NAME VARCHAR2(100) NOT NULL, /* 게시글 이름 */
	C_B_PRICE NUMBER NOT NULL /* 기본 가격 */
);

COMMENT ON TABLE CUSTOM_BOARD IS '커스터마이징 케이크 상세페이지';

COMMENT ON COLUMN CUSTOM_BOARD.C_B_NUM IS '게시글 번호';

COMMENT ON COLUMN CUSTOM_BOARD.M_ID IS '회원 아이디';

COMMENT ON COLUMN CUSTOM_BOARD.C_B_MINI_TITLE IS '게시글 소제목';

COMMENT ON COLUMN CUSTOM_BOARD.C_B_MINI_CONTENT IS '게시글 소내용';

COMMENT ON COLUMN CUSTOM_BOARD.C_B_CONTENT IS '게시글 내용';

COMMENT ON COLUMN CUSTOM_BOARD.C_B_LIKE IS '게시글 좋아요 수';

COMMENT ON COLUMN CUSTOM_BOARD.C_B_READCNT IS '게시글 조회 수';

COMMENT ON COLUMN CUSTOM_BOARD.C_B_TAG IS '게시글 태그';

COMMENT ON COLUMN CUSTOM_BOARD.C_B_WARN IS '예약시 주의사항';

COMMENT ON COLUMN CUSTOM_BOARD.C_B_NAME IS '게시글 이름';

COMMENT ON COLUMN CUSTOM_BOARD.C_B_PRICE IS '기본 가격';

CREATE UNIQUE INDEX PK_CUSTOM_BOARD
	ON CUSTOM_BOARD (
		C_B_NUM ASC
	);

ALTER TABLE CUSTOM_BOARD
	ADD
		CONSTRAINT PK_CUSTOM_BOARD
		PRIMARY KEY (
			C_B_NUM
		);

ALTER TABLE CUSTOM_BOARD
	ADD
		CONSTRAINT FK_MEMBER_TO_CUSTOM_BOARD
		FOREIGN KEY (
			M_ID
		)
		REFERENCES MEMBER (
			M_ID
		);
		
		
-- PRODUCT_BOARD 
ALTER TABLE PRODUCT_BOARD
	DROP
		CONSTRAINT FK_MEMBER_TO_PRODUCT_BOARD
		CASCADE;

ALTER TABLE PRODUCT_BOARD
	DROP
		PRIMARY KEY
		CASCADE
		KEEP INDEX;

DROP INDEX PK_PRODUCT_BOARD;

/* 완제품 케이크 상세페이지 */
DROP TABLE PRODUCT_BOARD 
	CASCADE CONSTRAINTS;

/* 완제품 케이크 상세페이지 */
CREATE TABLE PRODUCT_BOARD (
	P_B_NUM NUMBER NOT NULL, /* 게시글 번호 */
	M_ID VARCHAR2(50) NOT NULL, /* 회원 아이디 */
	P_NAME VARCHAR2(100) NOT NULL, /* 케이크 이름 */
	P_PRICE VARCHAR2(100) NOT NULL, /* 케이크 가격 */
	P_IMG VARCHAR2(100) NOT NULL, /* 케이크 이미지 */
	P_SIZE NUMBER NOT NULL, /* 케이크 규격 */
	P_CM VARCHAR2(20) NOT NULL, /* 케이크 크기(CM) */
	P_COUNT NUMBER NOT NULL, /* 케이크 재고 */
	P_COUNT_LIMIT NUMBER NOT NULL, /* 일일판매제한 개수 */
	P_B_MINI_TITLE VARCHAR2(100) NOT NULL, /* 게시글 소 제목 */
	P_B_MINI_CONTENT VARCHAR2(2000) NOT NULL, /* 게시글 소내용 */
	P_B_CONTENT VARCHAR2(4000) NOT NULL, /* 게시글 내용 */
	P_B_LIKE NUMBER NOT NULL, /* 게시글 좋아요 수 */
	P_B_READCNT NUMBER NOT NULL, /* 게시글 조회 수 */
	P_B_YN VARCHAR2(2) NOT NULL, /* 당일 구매여부 */
	P_B_WARN VARCHAR2(2000) NOT NULL, /* 예약시 주의사항 */
	P_B_TAG VARCHAR2(2000) NOT NULL /* 게시글 태그 */
);

COMMENT ON TABLE PRODUCT_BOARD IS '완제품 케이크 상세페이지';

COMMENT ON COLUMN PRODUCT_BOARD.P_B_NUM IS '게시글 번호';

COMMENT ON COLUMN PRODUCT_BOARD.M_ID IS '회원 아이디';

COMMENT ON COLUMN PRODUCT_BOARD.P_NAME IS '케이크 이름';

COMMENT ON COLUMN PRODUCT_BOARD.P_PRICE IS '케이크 가격';

COMMENT ON COLUMN PRODUCT_BOARD.P_IMG IS '케이크 이미지';

COMMENT ON COLUMN PRODUCT_BOARD.P_SIZE IS '케이크 규격';

COMMENT ON COLUMN PRODUCT_BOARD.P_CM IS '케이크 크기(CM)';

COMMENT ON COLUMN PRODUCT_BOARD.P_COUNT IS '케이크 재고';

COMMENT ON COLUMN PRODUCT_BOARD.P_COUNT_LIMIT IS '일일판매제한 개수';

COMMENT ON COLUMN PRODUCT_BOARD.P_B_MINI_TITLE IS '게시글 소 제목';

COMMENT ON COLUMN PRODUCT_BOARD.P_B_MINI_CONTENT IS '게시글 소내용';

COMMENT ON COLUMN PRODUCT_BOARD.P_B_CONTENT IS '게시글 내용';

COMMENT ON COLUMN PRODUCT_BOARD.P_B_LIKE IS '게시글 좋아요 수';

COMMENT ON COLUMN PRODUCT_BOARD.P_B_READCNT IS '게시글 조회 수';

COMMENT ON COLUMN PRODUCT_BOARD.P_B_YN IS '당일 구매여부';

COMMENT ON COLUMN PRODUCT_BOARD.P_B_WARN IS '예약시 주의사항';

COMMENT ON COLUMN PRODUCT_BOARD.P_B_TAG IS '게시글 태그';

CREATE UNIQUE INDEX PK_PRODUCT_BOARD
	ON PRODUCT_BOARD (
		P_B_NUM ASC
	);

ALTER TABLE PRODUCT_BOARD
	ADD
		CONSTRAINT PK_PRODUCT_BOARD
		PRIMARY KEY (
			P_B_NUM
		);

ALTER TABLE PRODUCT_BOARD
	ADD
		CONSTRAINT FK_MEMBER_TO_PRODUCT_BOARD
		FOREIGN KEY (
			M_ID
		)
		REFERENCES MEMBER (
			M_ID
		);
		

-- HOME_QNA
ALTER TABLE HOME_QNA
	DROP
		CONSTRAINT FK_MEMBER_TO_HOME_QNA
		CASCADE;

ALTER TABLE HOME_QNA
	DROP
		CONSTRAINT FK_HOME_QNA_TO_HOME_QNA
		CASCADE;

ALTER TABLE HOME_QNA
	DROP
		PRIMARY KEY
		CASCADE
		KEEP INDEX;

DROP INDEX PK_HOME_QNA;

/* 홈페이지 관련 QNA */
DROP TABLE HOME_QNA 
	CASCADE CONSTRAINTS;

/* 홈페이지 관련 QNA */
CREATE TABLE HOME_QNA (
	H_Q_NUM NUMBER NOT NULL, /* QNA 게시글 번호 */
	M_ID VARCHAR2(50) NOT NULL, /* QNA 게시글 글쓴이 */
	H_Q_CONTENT VARCHAR2(4000) NOT NULL, /* QNA 게시글 내용 */
	H_Q_TITLE VARCHAR2(500) NOT NULL, /* QNA 게시글 제목 */
	H_Q_DATE DATE NOT NULL, /* QNA 게시글 작성일 */
	H_Q_RE_REF NUMBER NOT NULL, /* 원글 참조 번호 */
	H_Q_RE_LEV NUMBER NOT NULL, /* 답글 레벨 */
	H_Q_RE_SEQ NUMBER NOT NULL /* 답글 시퀀스 */
);

COMMENT ON TABLE HOME_QNA IS '홈페이지 관련 QNA';

COMMENT ON COLUMN HOME_QNA.H_Q_NUM IS 'QNA 게시글 번호';

COMMENT ON COLUMN HOME_QNA.M_ID IS 'QNA 게시글 글쓴이';

COMMENT ON COLUMN HOME_QNA.H_Q_CONTENT IS 'QNA 게시글 내용';

COMMENT ON COLUMN HOME_QNA.H_Q_TITLE IS 'QNA 게시글 제목';

COMMENT ON COLUMN HOME_QNA.H_Q_DATE IS 'QNA 게시글 작성일';

COMMENT ON COLUMN HOME_QNA.H_Q_RE_REF IS '원글 참조 번호';

COMMENT ON COLUMN HOME_QNA.H_Q_RE_LEV IS '답글 레벨';

COMMENT ON COLUMN HOME_QNA.H_Q_RE_SEQ IS '답글 시퀀스';

CREATE UNIQUE INDEX PK_HOME_QNA
	ON HOME_QNA (
		H_Q_NUM ASC
	);

ALTER TABLE HOME_QNA
	ADD
		CONSTRAINT PK_HOME_QNA
		PRIMARY KEY (
			H_Q_NUM
		);

ALTER TABLE HOME_QNA
	ADD
		CONSTRAINT FK_MEMBER_TO_HOME_QNA
		FOREIGN KEY (
			M_ID
		)
		REFERENCES MEMBER (
			M_ID
		);

ALTER TABLE HOME_QNA
	ADD
		CONSTRAINT FK_HOME_QNA_TO_HOME_QNA
		FOREIGN KEY (
			H_Q_RE_REF
		)
		REFERENCES HOME_QNA (
			H_Q_NUM
		);
		

-- H_QNA_COM
ALTER TABLE H_QNA_COM
	DROP
		CONSTRAINT FK_MEMBER_TO_H_QNA_COM
		CASCADE;

ALTER TABLE H_QNA_COM
	DROP
		CONSTRAINT FK_H_QNA_COM_TO_H_QNA_COM
		CASCADE;

ALTER TABLE H_QNA_COM
	DROP
		PRIMARY KEY
		CASCADE
		KEEP INDEX;

DROP INDEX PK_H_QNA_COM;

/* 홈페이지 관련 QNA 댓글 */
DROP TABLE H_QNA_COM 
	CASCADE CONSTRAINTS;

/* 홈페이지 관련 QNA 댓글 */
CREATE TABLE H_QNA_COM (
	H_Q_C_NUM NUMBER NOT NULL, /* 홈페이지 QNA 댓글 번호 */
	H_Q_NUM NUMBER NOT NULL, /* 홈페이지 QNA 게시글 참조번호 */
	M_ID VARCHAR2(50) NOT NULL, /* 홈페이지 QNA 댓글 글쓴이 */
	H_Q_C_CONTENT VARCHAR2(4000) NOT NULL, /* 홈페이지 QNA 댓글 내용 */
	H_Q_C_DATE DATE NOT NULL, /* 홈페이지 QNA 댓글 작성날짜 */
	H_Q_C_RE_LEV NUMBER NOT NULL, /* 홈페이지 QNA 댓글 레벨 */
	H_Q_C_RE_SEQ NUMBER NOT NULL /* 홈페이지 QNA 댓글 시퀀스 */
);

COMMENT ON TABLE H_QNA_COM IS '홈페이지 관련 QNA 댓글';

COMMENT ON COLUMN H_QNA_COM.H_Q_C_NUM IS '홈페이지 QNA 댓글 번호';

COMMENT ON COLUMN H_QNA_COM.H_Q_NUM IS '홈페이지 QNA 게시글 참조번호';

COMMENT ON COLUMN H_QNA_COM.M_ID IS '홈페이지 QNA 댓글 글쓴이';

COMMENT ON COLUMN H_QNA_COM.H_Q_C_CONTENT IS '홈페이지 QNA 댓글 내용';

COMMENT ON COLUMN H_QNA_COM.H_Q_C_DATE IS '홈페이지 QNA 댓글 작성날짜';

COMMENT ON COLUMN H_QNA_COM.H_Q_C_RE_LEV IS '홈페이지 QNA 댓글 레벨';

COMMENT ON COLUMN H_QNA_COM.H_Q_C_RE_SEQ IS '홈페이지 QNA 댓글 시퀀스';

CREATE UNIQUE INDEX PK_H_QNA_COM
	ON H_QNA_COM (
		H_Q_C_NUM ASC
	);

ALTER TABLE H_QNA_COM
	ADD
		CONSTRAINT PK_H_QNA_COM
		PRIMARY KEY (
			H_Q_C_NUM
		);

ALTER TABLE H_QNA_COM
	ADD
		CONSTRAINT FK_MEMBER_TO_H_QNA_COM
		FOREIGN KEY (
			M_ID
		)
		REFERENCES MEMBER (
			M_ID
		);

ALTER TABLE H_QNA_COM
	ADD
		CONSTRAINT FK_H_QNA_COM_TO_H_QNA_COM
		FOREIGN KEY (
			H_Q_NUM
		)
		REFERENCES H_QNA_COM (
			H_Q_C_NUM
		);
		
		
-- PRODUCT_QNA
ALTER TABLE PRODUCT_QNA
	DROP
		CONSTRAINT FK_PRODUCT_BOARD_TO_PRODUCT_QNA
		CASCADE;

ALTER TABLE PRODUCT_QNA
	DROP
		PRIMARY KEY
		CASCADE
		KEEP INDEX;

DROP INDEX PK_PRODUCT_QNA;

/* 상품 관련 QNA */
DROP TABLE PRODUCT_QNA 
	CASCADE CONSTRAINTS;

/* 상품 관련 QNA */
CREATE TABLE PRODUCT_QNA (
	P_Q_NUM NUMBER NOT NULL, /* 상품 QNA 게시글 번호 */
	P_B_NUM NUMBER NOT NULL, /* 상품 원글 참조 번호 */
	M_ID VARCHAR2(100) NOT NULL, /* 상품 QNA 글쓴이 */
	P_Q_CONTENT VARCHAR2(4000) NOT NULL, /* 상품 QNA 글 내용 */
	P_Q_DATE DATE NOT NULL /* 상품 QNA 글 작성일 */
);

COMMENT ON TABLE PRODUCT_QNA IS '상품 관련 QNA';

COMMENT ON COLUMN PRODUCT_QNA.P_Q_NUM IS '상품 QNA 게시글 번호';

COMMENT ON COLUMN PRODUCT_QNA.P_B_NUM IS '상품 원글 참조 번호';

COMMENT ON COLUMN PRODUCT_QNA.M_ID IS '상품 QNA 글쓴이';

COMMENT ON COLUMN PRODUCT_QNA.P_Q_CONTENT IS '상품 QNA 글 내용';

COMMENT ON COLUMN PRODUCT_QNA.P_Q_DATE IS '상품 QNA 글 작성일';

CREATE UNIQUE INDEX PK_PRODUCT_QNA
	ON PRODUCT_QNA (
		P_Q_NUM ASC
	);

ALTER TABLE PRODUCT_QNA
	ADD
		CONSTRAINT PK_PRODUCT_QNA
		PRIMARY KEY (
			P_Q_NUM
		);

ALTER TABLE PRODUCT_QNA
	ADD
		CONSTRAINT FK_PRODUCT_BOARD_TO_PRODUCT_QNA
		FOREIGN KEY (
			P_B_NUM
		)
		REFERENCES PRODUCT_BOARD (
			P_B_NUM
		);

		
		
-- P_QNA_COM
ALTER TABLE P_QNA_COM
	DROP
		CONSTRAINT FK_PRODUCT_QNA_TO_P_QNA_COM
		CASCADE;

ALTER TABLE P_QNA_COM
	DROP
		CONSTRAINT FK_MEMBER_TO_P_QNA_COM
		CASCADE;

ALTER TABLE P_QNA_COM
	DROP
		PRIMARY KEY
		CASCADE
		KEEP INDEX;

DROP INDEX PK_P_QNA_COM;

/* 상풍 관련 QNA 댓글 */
DROP TABLE P_QNA_COM 
	CASCADE CONSTRAINTS;

/* 상풍 관련 QNA 댓글 */
CREATE TABLE P_QNA_COM (
	P_Q_C_NUM NUMBER NOT NULL, /* 상품 QNA 댓글 번호 */
	P_Q_NUM NUMBER NOT NULL, /* 상품 QNA 원글 참조 번호 */
	M_ID VARCHAR2(50) NOT NULL, /* 상품 QNA 댓글쓴이 */
	P_Q_C_CONTENT VARCHAR2(4000) NOT NULL, /* 상품 QNA 댓글 내용 */
	P_Q_C_DATE DATE NOT NULL /* 상품 QNA 댓글 작성날짜 */
);

COMMENT ON TABLE P_QNA_COM IS '상풍 관련 QNA 댓글';

COMMENT ON COLUMN P_QNA_COM.P_Q_C_NUM IS '상품 QNA 댓글 번호';

COMMENT ON COLUMN P_QNA_COM.P_Q_NUM IS '상품 QNA 원글 참조 번호';

COMMENT ON COLUMN P_QNA_COM.M_ID IS '상품 QNA 댓글쓴이';

COMMENT ON COLUMN P_QNA_COM.P_Q_C_CONTENT IS '상품 QNA 댓글 내용';

COMMENT ON COLUMN P_QNA_COM.P_Q_C_DATE IS '상품 QNA 댓글 작성날짜';

CREATE UNIQUE INDEX PK_P_QNA_COM
	ON P_QNA_COM (
		P_Q_C_NUM ASC
	);

ALTER TABLE P_QNA_COM
	ADD
		CONSTRAINT PK_P_QNA_COM
		PRIMARY KEY (
			P_Q_C_NUM
		);

ALTER TABLE P_QNA_COM
	ADD
		CONSTRAINT FK_PRODUCT_QNA_TO_P_QNA_COM
		FOREIGN KEY (
			P_Q_NUM
		)
		REFERENCES PRODUCT_QNA (
			P_Q_NUM
		);

ALTER TABLE P_QNA_COM
	ADD
		CONSTRAINT FK_MEMBER_TO_P_QNA_COM
		FOREIGN KEY (
			M_ID
		)
		REFERENCES MEMBER (
			M_ID
		);
		
		
-- PRODUCT_REVIEW
ALTER TABLE PRODUCT_REVIEW
	DROP
		CONSTRAINT FK_PRODUCT_BOARD_TO_PRODUCT_REVIEW
		CASCADE;

ALTER TABLE PRODUCT_REVIEW
	DROP
		CONSTRAINT FK_MEMBER_TO_PRODUCT_REVIEW
		CASCADE;

ALTER TABLE PRODUCT_REVIEW
	DROP
		PRIMARY KEY
		CASCADE
		KEEP INDEX;

DROP INDEX PK_PRODUCT_REVIEW;

/* 상품 리뷰 */
DROP TABLE PRODUCT_REVIEW 
	CASCADE CONSTRAINTS;

/* 상품 리뷰 */
CREATE TABLE PRODUCT_REVIEW (
	P_R_NUM NUMBER NOT NULL, /* 리뷰 글 번호 */
	P_B_NUM NUMBER NOT NULL, /* 원글 참조 번호 */
	M_ID VARCHAR2(50) NOT NULL, /* 리뷰 글쓴이 */
	P_R_CONTENT VARCHAR2(4000) NOT NULL, /* 리뷰 글 내용 */
	P_R_DATE DATE NOT NULL, /* 리뷰 글 작성일 */
	P_R_LIKE NUMBER NOT NULL, /* 리뷰 좋아요 수 */
	P_R_BLACK NUMBER NOT NULL, /* 리뷰 신고 수 */
	P_R_FILE VARCHAR2(1000), /* 리뷰 이미지 */
	P_R_STAR NUMBER NOT NULL /* 리뷰 별점 */
);

COMMENT ON TABLE PRODUCT_REVIEW IS '상품 리뷰';

COMMENT ON COLUMN PRODUCT_REVIEW.P_R_NUM IS '리뷰 글 번호';

COMMENT ON COLUMN PRODUCT_REVIEW.P_B_NUM IS '원글 참조 번호';

COMMENT ON COLUMN PRODUCT_REVIEW.M_ID IS '리뷰 글쓴이';

COMMENT ON COLUMN PRODUCT_REVIEW.P_R_CONTENT IS '리뷰 글 내용';

COMMENT ON COLUMN PRODUCT_REVIEW.P_R_DATE IS '리뷰 글 작성일';

COMMENT ON COLUMN PRODUCT_REVIEW.P_R_LIKE IS '리뷰 좋아요 수';

COMMENT ON COLUMN PRODUCT_REVIEW.P_R_BLACK IS '리뷰 신고 수';

COMMENT ON COLUMN PRODUCT_REVIEW.P_R_FILE IS '리뷰 이미지';

COMMENT ON COLUMN PRODUCT_REVIEW.P_R_STAR IS '리뷰 별점';

CREATE UNIQUE INDEX PK_PRODUCT_REVIEW
	ON PRODUCT_REVIEW (
		P_R_NUM ASC
	);

ALTER TABLE PRODUCT_REVIEW
	ADD
		CONSTRAINT PK_PRODUCT_REVIEW
		PRIMARY KEY (
			P_R_NUM
		);

ALTER TABLE PRODUCT_REVIEW
	ADD
		CONSTRAINT FK_PRODUCT_BOARD_TO_PRODUCT_REVIEW
		FOREIGN KEY (
			P_B_NUM
		)
		REFERENCES PRODUCT_BOARD (
			P_B_NUM
		);

ALTER TABLE PRODUCT_REVIEW
	ADD
		CONSTRAINT FK_MEMBER_TO_PRODUCT_REVIEW
		FOREIGN KEY (
			M_ID
		)
		REFERENCES MEMBER (
			M_ID
		);
		
		
-- P_REVIEW_COM
ALTER TABLE P_REVIEW_COM
	DROP
		CONSTRAINT FK_PRODUCT_REVIEW_TO_P_REVIEW_COM
		CASCADE;

ALTER TABLE P_REVIEW_COM
	DROP
		PRIMARY KEY
		CASCADE
		KEEP INDEX;

DROP INDEX PK_P_REVIEW_COM;

/* 상품 리뷰 댓글 */
DROP TABLE P_REVIEW_COM 
	CASCADE CONSTRAINTS;

/* 상품 리뷰 댓글 */
CREATE TABLE P_REVIEW_COM (
	P_R_C_NUM NUMBER NOT NULL, /* 리뷰 댓글 번호 */
	P_R_NUM NUMBER NOT NULL, /* 리뷰 원글 참조 번호 */
	P_R_C_CONTENT VARCHAR2(4000) NOT NULL, /* 리뷰 댓글 내용 */
	P_R_C_DATE DATE NOT NULL /* 리뷰 댓글 작성일 */
);

COMMENT ON TABLE P_REVIEW_COM IS '상품 리뷰 댓글';

COMMENT ON COLUMN P_REVIEW_COM.P_R_C_NUM IS '리뷰 댓글 번호';

COMMENT ON COLUMN P_REVIEW_COM.P_R_NUM IS '리뷰 원글 참조 번호';

COMMENT ON COLUMN P_REVIEW_COM.P_R_C_CONTENT IS '리뷰 댓글 내용';

COMMENT ON COLUMN P_REVIEW_COM.P_R_C_DATE IS '리뷰 댓글 작성일';

CREATE UNIQUE INDEX PK_P_REVIEW_COM
	ON P_REVIEW_COM (
		P_R_C_NUM ASC
	);

ALTER TABLE P_REVIEW_COM
	ADD
		CONSTRAINT PK_P_REVIEW_COM
		PRIMARY KEY (
			P_R_C_NUM
		);

ALTER TABLE P_REVIEW_COM
	ADD
		CONSTRAINT FK_PRODUCT_REVIEW_TO_P_REVIEW_COM
		FOREIGN KEY (
			P_R_NUM
		)
		REFERENCES PRODUCT_REVIEW (
			P_R_NUM
		);
		