-- DELIVERY_BASIC
ALTER TABLE DELIVERY_BASIC
	DROP
		CONSTRAINT FK_PRODUCT_ORDER_TO_DELIVERY_BASIC
		CASCADE;

ALTER TABLE DELIVERY_BASIC
	DROP
		PRIMARY KEY
		CASCADE
		KEEP INDEX;

DROP INDEX PK_DELIVERY_BASIC;

/* 배송 기본 정보 */
DROP TABLE DELIVERY_BASIC 
	CASCADE CONSTRAINTS;

/* 배송 기본 정보 */
CREATE TABLE DELIVERY_BASIC (
	D_NUM VARCHAR2(20) NOT NULL, /* 운송장 번호 */
	P_O_NUM NUMBER NOT NULL, /* 주문번호 */
	D_COMPANY VARCHAR2(300) NOT NULL /* 택배사 */
);

COMMENT ON TABLE DELIVERY_BASIC IS '배송 기본 정보';

COMMENT ON COLUMN DELIVERY_BASIC.D_NUM IS '운송장 번호';

COMMENT ON COLUMN DELIVERY_BASIC.P_O_NUM IS '주문번호';

COMMENT ON COLUMN DELIVERY_BASIC.D_COMPANY IS '택배사';

CREATE UNIQUE INDEX PK_DELIVERY_BASIC
	ON DELIVERY_BASIC (
		D_NUM ASC
	);

ALTER TABLE DELIVERY_BASIC
	ADD
		CONSTRAINT PK_DELIVERY_BASIC
		PRIMARY KEY (
			D_NUM
		);

ALTER TABLE DELIVERY_BASIC
	ADD
		CONSTRAINT FK_PRODUCT_ORDER_TO_DELIVERY_BASIC
		FOREIGN KEY (
			P_O_NUM
		)
		REFERENCES PRODUCT_ORDER (
			P_O_NUM
		);
		
		
-- DELIVERY
ALTER TABLE DELIVERY
	DROP
		CONSTRAINT FK_DELIVERY_BASIC_TO_DELIVERY
		CASCADE;

/* 배송관련 테이블 */
DROP TABLE DELIVERY 
	CASCADE CONSTRAINTS;

/* 배송관련 테이블 */
CREATE TABLE DELIVERY (
	D_NUM VARCHAR2(20) NOT NULL, /* 운송장 번호 */
	D_DATE DATE NOT NULL, /* 처리 일시 */
	D_LOCATION VARCHAR2(100) NOT NULL, /* 택배 현재 위치 */
	DV_STATUS VARCHAR2(50) NOT NULL, /* 배송 상태 */
	DM_CP VARCHAR2(20) /* 배송기사 전화번호 */
);

COMMENT ON TABLE DELIVERY IS '배송관련 테이블';

COMMENT ON COLUMN DELIVERY.D_NUM IS '운송장 번호';

COMMENT ON COLUMN DELIVERY.D_DATE IS '처리 일시';

COMMENT ON COLUMN DELIVERY.D_LOCATION IS '택배 현재 위치';

COMMENT ON COLUMN DELIVERY.DV_STATUS IS '배송 상태';

COMMENT ON COLUMN DELIVERY.DM_CP IS '배송기사 전화번호';

ALTER TABLE DELIVERY
	ADD
		CONSTRAINT FK_DELIVERY_BASIC_TO_DELIVERY
		FOREIGN KEY (
			D_NUM
		)
		REFERENCES DELIVERY_BASIC (
			D_NUM
		);
		
		
-- STATUS
ALTER TABLE STATUS
	DROP
		PRIMARY KEY
		CASCADE
		KEEP INDEX;

DROP INDEX PK_STATUS;

/* 주문 진행 단계 */
DROP TABLE STATUS 
	CASCADE CONSTRAINTS;

/* 주문 진행 단계 */
CREATE TABLE STATUS (
	S_NUM NUMBER NOT NULL, /* 주문 진행단계 번호 */
	S_STATUS VARCHAR2(20) NOT NULL /* 주문 진행단계 설명 */
);

COMMENT ON TABLE STATUS IS '주문 진행 단계';

COMMENT ON COLUMN STATUS.S_NUM IS '주문 진행단계 번호';

COMMENT ON COLUMN STATUS.S_STATUS IS '주문 진행단계 설명';

CREATE UNIQUE INDEX PK_STATUS
	ON STATUS (
		S_NUM ASC
	);

ALTER TABLE STATUS
	ADD
		CONSTRAINT PK_STATUS
		PRIMARY KEY (
			S_NUM
		);