--create user likeycakey identified by likeycakey;
--grant resource, connect to likeycakey;

-- 회원 코드 설정 (M_NUM : PK)
DROP TABLE MEMBER_CODE CASCADE
CREATE TABLE MEMBER_CODE
(
	M_NUM NUMBER,
	M_TYPE VARCHAR2(12) NOT NULL,
	CONSTRAINT MCODE_PK_MNUM PRIMARY KEY (M_NUM)
);

INSERT INTO MEMBER_CODE
VALUES(1, 'ADMIN');

INSERT INTO MEMBER_CODE
VALUES(2, 'NORMAL');

INSERT INTO MEMBER_CODE
VALUES(3, 'BIZ');

-- 일반회원 및 관리자 정보 (M_ID : PK)
DROP TABLE MEMBER;
CREATE TABLE MEMBER
(
	M_ID VARCHAR2(50),
	M_PW VARCHAR2(50) NOT NULL,
	M_NAME VARCHAR2(50) NOT NULL,
	M_EMAIL VARCHAR2(100),
	M_POST VARCHAR2(10),
	M_BASIC_ADDR VARCHAR2(1000),
	M_DETAIL_ADDR VARCHAR2(1000),
	M_PHOTO VARCHAR2(2000),
	M_CP VARCHAR2(50),
	M_NUM NUMBER,
	CONSTRAINT MEM_PK_MID PRIMARY KEY (M_ID),
	CONSTRAINT MEM_FK_MNUM FOREIGN KEY (M_NUM) REFERENCES MEMBER_CODE (M_NUM)
);


INSERT INTO MEMBER VALUES("dodo123", "dodo123", "도도", "dodo123@naver.com", 
"13402", "경기도 성남시 분당구 판교로 50번길", "판교휴먼시아 1단지 101동 1103호", "img", "010-1234-5678", 2);


CREATE TABLE TEST 
(
	M_DETAIL VARCHAR2(1000)
)
DROP TABLE TEST
INSERT INTO TEST VALUES("판교휴먼시아 1단지 101동 1103호")
SELECT LENGTH (M_DETAIL_ADDR) FROM MEMBER


-- 기업회원 정보
DROP TABLE MEMBER_BIZ;
CREATE TABLE MEMBER_BIZ
(
	M_ID VARCHAR2(50),
	BIZ_NAME VARCHAR2(50) NOT NULL,
	BIZ_PN VARCHAR2(20) NOT NULL,
	BIZ_NUM VARCHAR2(50) NOT NULL,
	BIZ_EMAIL VARCHAR2(50) NOT NULL,
	BIZ_DELIVERY NUMBER,
	MASTER_NAME VARCHAR2(50) NOT NULL,
	CONSTRAINT MEMBIZ_FK_MID FOREIGN KEY (M_ID) REFERENCES MEMBER (M_ID)
);